### ISSUE TITLE
WebKit bots having too many TIME_WAIT sockets

### ISSUE THREAD

**Issue by youennf** [w3c/wptserve#108] opened 2016-11-16 03:12 UTC
As shown in https://bugs.webkit.org/show_bug.cgi?id=159166#c21, some WebKit bots WPT servers (localhost-running) may have too many sockets in the TIME_WAIT state. This seems to prevent running the tests correctly for some runs.

Has anybody encountered the issue?
Maybe keep-alive should be implemented in wptserve to reduce the risk?

**Comment by youennf** [comment] 2016-11-16 16:13
Looking at the code, it seems keep-alive is in action.
Not sure why we are seeing so much TIME_WAIT sockets then.

**Comment by youennf** [comment] 2016-11-16 16:43
It might be that mote responses have no content-length header

**Comment by gsnedders** [comment] 2016-11-16 17:22
I spent a few hours last week trying to work out why under high load wptserve seems to sometimes hang, using `ab`—on OS X, it consistently stopped responding at c.16500, with all connections after that getting stuck in SYN_SENT. I didn't really get anywhere very useful, though! May well be related, though?

In principle, any response without Content-Length should have the connection closed by the server after the end of the response. If that's not true, we should fix that.

**Comment by gsnedders** [comment] 2016-11-16 17:48
I have some memory of @jgraham or @Ms2ger having some reason why #86 didn't get merged.

That said, we shouldn't have them stuck in TIME_WAIT even without socket reuse.

**Comment by gsnedders** [comment] 2016-11-16 17:49
We've also had issues with w3c-test.org sometimes stopping responding, so I suspect there might be some underlying issue regardless.

**Comment by gsnedders** [comment] 2017-01-30 22:04
FWIW, I tried to look into why this happened and I couldn't figure out why it stopped working at the specific point it did looking at DTrace. That said, I've never tried to deal with anything at this level on OS X previously. Equally, I couldn't reproduce it on Linux artificially limiting number of sockets.

**Comment by wpt-issue-mover** [comment] 2017-11-20 16:19
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/8369; please continue all discussion there.

**Closed by wpt-issue-mover** 2017-11-20 16:19 UTC
